spring.datasource.url=jdbc:h2:mem:beneficio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.platform=h2

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# API docs
# Using springdoc default paths (v3 api docs + swagger-ui)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config

